### ISSUE TITLE
Conferir se as rodadas do HC podem criar mais clusters

### ISSUE THREAD

**Issue by marciobarros** [marciobarros/GALimitedSize#3]
O algoritmo está gerando uma solução inicial com um número sorteado de clusters. Ficamos na dúvida sobre a capacidade do HC em criar novos clusters. Uma forma fácil de identificar isto é partir de uma solução inicial com apenas um cluster e ver se o HC gera soluções com dois ou mais clusters.

**Comment by richardf** [comment]
A execução da HC é dividida em duas etapas:

1) Criação da solução inicial, com a função [generateSolution](https://github.com/richardf/GALimitedSize/blob/master/src/sobol/problems/clustering/hc/HillClimbingLimitedSizeClustering.java#L81-L106) que gera uma solução onde cada cluster terá [minClusterSize, maxClusterSize] elementos. Este tamanho inicial é sorteado.

2) A busca local na solução inicial é realizada pela função [NeighborhoodVisitorResult](https://github.com/richardf/GALimitedSize/blob/master/src/sobol/problems/clustering/hc/HillClimbingLimitedSizeClustering.java#L169-L212). 

``` java
     for (int i = 0; i < classCount; i++)
            for (int j = 0; j < clusterCount; j++)
```

A BL é executada em cada classe (for externo), trocando-a por outro cluster (for interno). Como o tamanho do cluster (clusterCount) está no for, não há como criar novos clusters na busca.

Mesmo alterando o for, a busca como é feita não permitirá a criação de novos clusters, pois esta se baseia na troca de elementos um a um. Como existe a restrição de tamanho mínimo para um cluster, a solução gerada não seria considerada válida.

Pode-se pensar em alterar a busca local ou talvez deixar a validação da solução apenas para o fim da sua execução.

**Comment by richardf** [comment]
Ficou acordado que, por enquanto, deixaremos o algoritmo como está.
